version: "3"

services:
  app:
    build:
      context: ""

    image: api_image

    ports:
      - "8000:8000"
      
    restart: always

    command: >
      sh -c "
        python database/create_table.py &&
        uvicorn api.auth:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - .:/app
      
    depends_on:
      - postgresdb
      - mongodb
      
    networks:
      - monreseau  

    links:
      - postgresdb
      - mongodb
 
  converter:
    build:
      context: ./converter

    image: converter_image

    restart: always

    command: >
      sh -c "
        ls -la && 
        pwd && 
        uvicorn route.api_convert:app --host 0.0.0.0 --port 8001 --reload
      "

    ports:
      - "8001:8001"


    volumes:
      - ./converter:/app
      
    depends_on:
      - postgresdb
      - mongodb
      - app
      
    networks:
      - monreseau  

    links:
      - postgresdb
      - mongodb
      - app


  postgresdb:

    image: postgres:14.1-alpine

    networks:
      - monreseau    

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres


  mongodb:

    image: mongo

    networks:
      - monreseau  

    ports:
      - 27017:27017

  admine:

    image: adminer
    restart: always
    depends_on:
      - postgresdb
    ports:
      - 8080:8080
    networks:
      - monreseau    
    links:
      - postgresdb

networks:
  monreseau:
     name: monreseau


  